### ISSUE TITLE
another build  issue

### ISSUE THREAD

**Issue by xuyan1972** [google/mr4c#10]
the last step  ./tools/build_yarn.  on the end ,all test failed ,no other error.
do-test:
    [junit] TEST com.google.mr4c.nativec.ExternalAlgorithmDataSerializerTest FAILED
    [junit] TEST com.google.mr4c.nativec.ExternalAlgorithmSerializerTest FAILED
    [junit] TEST com.google.mr4c.nativec.ExternalDatasetSerializerTest FAILED
    [junit] TEST com.google.mr4c.nativec.jna.JnaExternalEntryTest FAILED
    [junit] Tests FAILED

BUILD FAILED
then  in dist directory ,no any jar package  ,how to solve?

**Comment by unlimitedly** [comment]
Hello , I have the same problem when build it,do you solved it?

**Comment by xuyan1972** [comment]
see reports directory check corresponding file , then found libstdc++ library calling path is error ,IT CALL wrong PATH,  USING ld_library_path has no effect , usr ln command   ,link right calling  libstdc++ file to /usr/lib64/ then no problem build ok.
