### ISSUE TITLE
ABOUT gdaal ISSUE

### ISSUE THREAD

**Issue by xuyan1972** [google/mr4c#12]
Now I want save file into hdfs ,then read them by gdal interface(RastIO) ,then write result to other HDFS file by gdal interface (etc :create ,,rastIO) .Can anyone tell me the code outline of this process?
Dataset\* input = data.getInputDataset("imageIn");
std::set<DataKey> keys = input->getAllFileKeys();
Dataset\* outputHist = data.getOutputDataset("out");
for ( std::set<DataKey>::iterator i = keys.begin(); i != keys.end(); i++ ) {  
    DataKey myKey = _i;
    DataFile_ skyFile = input->getDataFile(myKey);
    std::string inputFileName = myKey.toName("__")+"_input";
    GDALMemoryFile inputMemFile(inputFileName, *skyFile);
    GDALDataset \* poDataset = inputMemFile.getGDALDataset();

```
    //then how to create new hdfs file  by gdal and add to outputHist 
    .....
```

**Comment by mitchwuzhere** [comment]
Please post questions like this to our google group: https://groups.google.com/forum/#!forum/mr4c
